#pragma once

// From glfw3.h
#define NIGHT_MOUSE_BUTTON_1         0
#define NIGHT_MOUSE_BUTTON_2         1
#define NIGHT_MOUSE_BUTTON_3         2
#define NIGHT_MOUSE_BUTTON_4         3
#define NIGHT_MOUSE_BUTTON_5         4
#define NIGHT_MOUSE_BUTTON_6         5
#define NIGHT_MOUSE_BUTTON_7         6
#define NIGHT_MOUSE_BUTTON_8         7
#define NIGHT_MOUSE_BUTTON_LAST      NIGHT_MOUSE_BUTTON_8
#define NIGHT_MOUSE_BUTTON_LEFT      NIGHT_MOUSE_BUTTON_1
#define NIGHT_MOUSE_BUTTON_RIGHT     NIGHT_MOUSE_BUTTON_2
#define NIGHT_MOUSE_BUTTON_MIDDLE    NIGHT_MOUSE_BUTTON_3